version: '3.8'

services:
  flask-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-backend
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/vehicle_db
    volumes:
      - .:/app

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build:
      context: ../frontend
      dockerfile: dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000 (adjust as needed for your frontend framework)
    volumes:
      - ../frontend:/app # Mount the frontend code for live reloading (optional but recommended)
      - /app/node_modules # Create an anonymous volume for node_modules to prevent host overwriting

volumes:
  mongo_data:
